# numpy ndarray 对象

ndarray是用于存放同类型元素的多维数组，下标以0为开始。
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
# ndmin
import numpy as np
a = np.array([1, 2, 3], ndmin = 2)
print(a)

[[1 2 3]]


In [4]:
# dtype
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


# numpy 数据类型

# numpy 数组属性

In [5]:
# ndim
# 返回数组的秩
import numpy as np
a = np.arange(24)
print(a.ndim)
a = a.reshape(2, 4, 3)
print(a.ndim)

1
3


In [6]:
# shape
# 返回元组，代表数组的形状
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape, '\n--------')
# shape属性可以用于调整数组形状，效果等同于reshape
a.shape = (3, 2) #a = a.reshape(3, 2)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3) 
--------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [7]:
# itemsize
# 以字节形式返回数组中每个元素的大小
import numpy as np 
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print(x.itemsize)
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print(y.itemsize)

1
8


In [8]:
# flags
# 返回ndarray对象的内存信息

In [9]:
import numpy as np 
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


# numpy 创建数组
除底层ndarray构造器外，还可以通过以下几种方式来创建

## empty
创建指定形状、数据类型且未初始化的数组
```python
numpy.empty(shape, dtype = float, order = 'C')
```
- shape：数组形状
- dtype：数据类型，可选
- order：有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [10]:
import numpy as np
x = np.empty([3, 2], dtype = int)
print(x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


## zeros
创建指定大小，全0数组
```python
numpy.zeros(shape, dtype = float, order = 'C')
```

In [11]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[ 0.  0.  0.  0.  0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## ones
创建指定大小，全1数组
```python
numpy.ones(shape, dtype = None, order = 'C')
```

In [12]:
import numpy as np
 
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[ 1.  1.  1.  1.  1.]
[[1 1]
 [1 1]]


# 从已有数组创建数组

## asarray
```python
numpy.asarray(a, dtype = None, order = None)
```
- a	任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组
- dtype	数据类型，可选
- order	可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。