# numpy ndarray 对象

ndarray是用于存放同类型元素的多维数组，下标以0为开始。
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
# ndmin
import numpy as np
a = np.array([1, 2, 3], ndmin = 2)
print(a)

[[1 2 3]]


In [4]:
# dtype
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# numpy 数据类型

# numpy 数组属性

In [5]:
# ndim
# 返回数组的秩
import numpy as np
a = np.arange(24)
print(a.ndim)
a = a.reshape(2, 4, 3)
print(a.ndim)

1
3


In [6]:
# shape
# 返回元组，代表数组的形状
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape, '\n--------')
# shape属性可以用于调整数组形状，效果等同于reshape
a.shape = (3, 2) #a = a.reshape(3, 2)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3) 
--------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [7]:
# itemsize
# 以字节形式返回数组中每个元素的大小
import numpy as np 
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print(x.itemsize)
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print(y.itemsize)

1
8


In [8]:
# flags
# 返回ndarray对象的内存信息

In [9]:
import numpy as np 
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# numpy 创建数组
除底层ndarray构造器外，还可以通过以下几种方式来创建

## empty
创建指定形状、数据类型且未初始化的数组
```python
numpy.empty(shape, dtype = float, order = 'C')
```
- shape：数组形状
- dtype：数据类型，可选
- order：有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [10]:
import numpy as np
x = np.empty([3, 2], dtype = int)
print(x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


## zeros
创建指定大小，全0数组
```python
numpy.zeros(shape, dtype = float, order = 'C')
```

In [11]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## ones
创建指定大小，全1数组
```python
numpy.ones(shape, dtype = None, order = 'C')
```

In [12]:
import numpy as np
 
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


# 从已有数组创建数组

## asarray
```python
numpy.asarray(a, dtype = None, order = None)
```
- a	任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组
- dtype	数据类型，可选
- order	可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [13]:
import numpy as np 
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [14]:
import numpy as np 
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)

[(1, 2, 3) (4, 5)]


In [15]:
import numpy as np 
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


## frombuffer
```python
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```
可实现动态数组，接收buffer输入参数，以流的形式读入转化成ndarray对象。
- buffer	可以是任意对象，会以流的形式读入。
- dtype	返回数组的数据类型，可选
- count	读取的数据数量，默认为-1，读取所有数据。
- offset	读取的起始位置，默认为0。
##### 注意
当buffer是字符串时，python3默认使用Unicode类型，要转化成bytestring在原字符串前加b

In [16]:
import numpy as np 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


## fromiter
```python
numpy.fromiter(iterable, dtype, count=-1)
```
可从迭代对象中建立ndarray对象，返回一维数组。
- iterable	可迭代对象
- dtype	返回数组的数据类型
- count	读取的数据数量，默认为-1，读取所有数据

In [17]:
import numpy as np 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


# 从数值范围创建数组

## arange
```python
numpy.arange(start, stop, step, dtype)
```
- start	起始值，默认为0
- stop	终止值（不包含）
- step	步长，默认为1
- dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

In [18]:
import numpy as np
x = np.arange(5)  
print (x)

[0 1 2 3 4]


In [19]:
import numpy as np
x = np.arange(10,20,2, dtype =  float)  
print (x)

[10. 12. 14. 16. 18.]


## linspace
```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
创建等差数列
- start	序列的起始值
- stop	序列的终止值，如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
- retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
- dtype	ndarray 的数据类型

In [20]:
import numpy as np
a = np.linspace(1,10,10)
print(a)
a = np.linspace(1,10,9, endpoint =  False)  
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## logspace
```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
创建等比数列
- start	序列的起始值为：base ** start
- stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
- base	对数 log 的底数。
- dtype	ndarray 的数据类型

In [22]:
import numpy as np
# 默认底数是 10
a = np.logspace(1.0,2.0,num = 10)  
print (a)
a = np.logspace(0,9,10,base=2)
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


# 切片和索引

ndarray数组可以基于0-n的下标进行索引，切片可使用内置slice函数

In [23]:
import numpy as np
 
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]
[2 4 6]


In [27]:
import numpy as np
 
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9] 
print(a[5])
print(a[2:])
print(a[2:5])

5
[2 3 4 5 6 7 8 9]
[2 3 4]


In [28]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print (a)
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


# 高级索引

## 整数数组索引

In [29]:
# 获取（0,0）（1,1）（2,0）位置的元素
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = x[[0,1,2],[0,1,0]]
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 7]


In [34]:
# 获取顶点元素，行索引[0,0][3,3],列索引[0,2][0,2]
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [36]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3, [1,2]]
d = a[..., 1:]
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 布尔索引
通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

In [39]:
# 获取大于5的元素
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x[x > 5])

[ 6  7  8  9 10 11]


In [40]:
# 获取非NaN元素
import numpy as np
a = np.array([np.nan, 1, 2, np.nan, 4, 5])
print(a[~np.isnan(a)])

[1. 2. 4. 5.]


## 花式索引
花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

花式索引跟切片不一样，它总是将数据复制到新数组中。

In [41]:
import numpy as np
x=np.arange(32).reshape((8,4))
print(x)
print(x[[4,2,1,7]]) #顺序索引数组
print(x[[-4,-2,-1,-7]]) #倒序索引数组
print(x[np.ix_([1,5,7,2],[0,3,1,2])]) #多个索引数组（要使用np.ix_）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
