# numpy ndarray 对象

ndarray是用于存放同类型元素的多维数组，下标以0为开始。
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
# ndmin
import numpy as np
a = np.array([1, 2, 3], ndmin = 2)
print(a)

[[1 2 3]]


In [5]:
# dtype
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


# numpy 数据类型

# numpy 数组属性

In [7]:
# ndim
import numpy as np
a = np.arange(24)
print(a.ndim)
a = a.reshape(2, 4, 3)
print(a.ndim)

1
3
