# numpy ndarray 对象

ndarray是用于存放同类型元素的多维数组，下标以0为开始。
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
# ndmin
import numpy as np
a = np.array([1, 2, 3], ndmin = 2)
print(a)

[[1 2 3]]


In [4]:
# dtype
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# numpy 数据类型

# numpy 数组属性

In [5]:
# ndim
# 返回数组的秩
import numpy as np
a = np.arange(24)
print(a.ndim)
a = a.reshape(2, 4, 3)
print(a.ndim)

1
3


In [6]:
# shape
# 返回元组，代表数组的形状
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape, '\n--------')
# shape属性可以用于调整数组形状，效果等同于reshape
a.shape = (3, 2) #a = a.reshape(3, 2)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3) 
--------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [7]:
# itemsize
# 以字节形式返回数组中每个元素的大小
import numpy as np 
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print(x.itemsize)
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print(y.itemsize)

1
8


In [8]:
# flags
# 返回ndarray对象的内存信息

In [9]:
import numpy as np 
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# numpy 创建数组
除底层ndarray构造器外，还可以通过以下几种方式来创建

## empty
创建指定形状、数据类型且未初始化的数组
```python
numpy.empty(shape, dtype = float, order = 'C')
```
- shape：数组形状
- dtype：数据类型，可选
- order：有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [10]:
import numpy as np
x = np.empty([3, 2], dtype = int)
print(x)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


## zeros
创建指定大小，全0数组
```python
numpy.zeros(shape, dtype = float, order = 'C')
```

In [11]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## ones
创建指定大小，全1数组
```python
numpy.ones(shape, dtype = None, order = 'C')
```

In [12]:
import numpy as np
 
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


# 从已有数组创建数组

## asarray
```python
numpy.asarray(a, dtype = None, order = None)
```
- a	任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组
- dtype	数据类型，可选
- order	可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [13]:
import numpy as np 
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [14]:
import numpy as np 
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)

[(1, 2, 3) (4, 5)]


In [15]:
import numpy as np 
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


## frombuffer
```python
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```
可实现动态数组，接收buffer输入参数，以流的形式读入转化成ndarray对象。
- buffer	可以是任意对象，会以流的形式读入。
- dtype	返回数组的数据类型，可选
- count	读取的数据数量，默认为-1，读取所有数据。
- offset	读取的起始位置，默认为0。
##### 注意
当buffer是字符串时，python3默认使用Unicode类型，要转化成bytestring在原字符串前加b

In [16]:
import numpy as np 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


## fromiter
```python
numpy.fromiter(iterable, dtype, count=-1)
```
可从迭代对象中建立ndarray对象，返回一维数组。
- iterable	可迭代对象
- dtype	返回数组的数据类型
- count	读取的数据数量，默认为-1，读取所有数据

In [17]:
import numpy as np 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


# 从数值范围创建数组

## arange
```python
numpy.arange(start, stop, step, dtype)
```
- start	起始值，默认为0
- stop	终止值（不包含）
- step	步长，默认为1
- dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

In [18]:
import numpy as np
x = np.arange(5)  
print (x)

[0 1 2 3 4]


In [19]:
import numpy as np
x = np.arange(10,20,2, dtype =  float)  
print (x)

[10. 12. 14. 16. 18.]


## linspace
```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
创建等差数列
- start	序列的起始值
- stop	序列的终止值，如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
- retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
- dtype	ndarray 的数据类型

In [20]:
import numpy as np
a = np.linspace(1,10,10)
print(a)
a = np.linspace(1,10,9, endpoint =  False)  
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## logspace
```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
创建等比数列
- start	序列的起始值为：base ** start
- stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
- base	对数 log 的底数。
- dtype	ndarray 的数据类型

In [21]:
import numpy as np
# 默认底数是 10
a = np.logspace(1.0,2.0,num = 10)  
print (a)
a = np.logspace(0,9,10,base=2)
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


# 切片和索引

ndarray数组可以基于0-n的下标进行索引，切片可使用内置slice函数

In [22]:
import numpy as np
 
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]
[2 4 6]


In [23]:
import numpy as np
 
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9] 
print(a[5])
print(a[2:])
print(a[2:5])

5
[2 3 4 5 6 7 8 9]
[2 3 4]


In [24]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print (a)
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


# 高级索引

## 整数数组索引

In [25]:
# 获取（0,0）（1,1）（2,0）位置的元素
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = x[[0,1,2],[0,1,0]]
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 7]


In [26]:
# 获取顶点元素，行索引[0,0][3,3],列索引[0,2][0,2]
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [27]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3, [1,2]]
d = a[..., 1:]
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 布尔索引
通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

In [28]:
# 获取大于5的元素
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x[x > 5])

[ 6  7  8  9 10 11]


In [29]:
# 获取非NaN元素
import numpy as np
a = np.array([np.nan, 1, 2, np.nan, 4, 5])
print(a[~np.isnan(a)])

[1. 2. 4. 5.]


## 花式索引
花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

花式索引跟切片不一样，它总是将数据复制到新数组中。

In [30]:
import numpy as np
x=np.arange(32).reshape((8,4))
print(x)
print(x[[4,2,1,7]]) #顺序索引数组
print(x[[-4,-2,-1,-7]]) #倒序索引数组
print(x[np.ix_([1,5,7,2],[0,3,1,2])]) #多个索引数组（要使用np.ix_）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


# 广播

In [31]:
import numpy as np 
 
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [32]:
#运算数组形状不同时，自动触发广播机制
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b) #即a+np.tile(b,(4,1))

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


**广播的规则:**

- 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
- 输出数组的形状是输入数组形状的各个维度上的最大值。
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
- 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

**简单理解**：对两个数组，分别比较他们的每一个维度（若其中一个数组没有当前维度则忽略），满足：

- 数组拥有相同形状。
- 当前维度的值相等。
- 当前维度的值有一个是 1。
若条件不满足，抛出 **"ValueError: frames are not aligned"** 异常。

# 迭代数组

迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。

迭代器最基本的任务的可以完成对数组元素的访问。

In [33]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a):
    print(x, end=", ")

[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

### 控制遍历顺序
- for x in np.nditer(a, order='F'):Fortran order，即是列序优先；
- for x in np.nditer(a.T, order='C'):C order，即是行序优先；

### 修改数组元素值
nditer 对象有另一个可选参数 op_flags。 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only），为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式。

In [34]:
import numpy as np
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
for x in np.nditer(a, op_flags=['readwrite']): 
    x[...]=2*x 
print ('修改后的数组是：')
print (a)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


### 使用外部循环
nditer类的构造器拥有flags参数，它可以接受下列值：
- c_index	可以跟踪 C 顺序的索引
- f_index	可以跟踪 Fortran 顺序的索引
- multi-index	每次迭代可以跟踪一种索引类型
- external_loop	给出的值是具有多个值的一维数组，而不是零维数组

In [35]:
# 遍历每列，合并为一维数组
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('修改后的数组是：')
for x in np.nditer(a, flags =  ['external_loop'], order =  'F'):  
   print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
修改后的数组是：
[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 

### 广播迭代
如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。 假设数组a的维度为3X4，数组b的维度为 1X4 ，则使用以下迭代器（数组b被广播到a的大小）。

In [36]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print (a)
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

# 数组操作
处理数组的函数大致分类：
- 修改数组形状
- 翻转数组
- 修改数组维度
- 连接数组
- 分割数组
- 数组元素的添加与删除

## 修改数组形状
- reshape	不改变数据的条件下修改形状
- flat	数组元素迭代器
- flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
- ravel	返回展开数组

### reshape
可以在不改变数据的条件下修改形状

```python
numpy.reshape(arr, newshape, order='C')
```

- arr：要修改形状的数组
- newshape：整数或者整数数组，新的形状应当兼容原有形状
- order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。

```python
import numpy as np
a = np.arange(8)
b = a.reshape(4,2)
```

### ndarray.flat
是一个数组元素迭代器

```python
import numpy as np
a = np.arange(9).reshape(3,3) 
print ('原始数组：')
for row in a:
    print (row)
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)
```

### ndarray.flatten
返回一份数组拷贝，对拷贝所做的修改不会影响原始数组

```python
ndarray.flatten(order='C')
```

- order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

```python
import numpy as np
a = np.arange(8).reshape(2,4)
print ('展开的数组：')
print (a.flatten())
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'F'))
```

### ravel
展平数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组。

```python
numpy.ravel(a, order='C')
```

## 翻转数组

- transpose	对换数组的维度
- ndarray.T	和 self.transpose() 相同
- rollaxis	向后滚动指定的轴
- swapaxes	对换数组的两个轴

numpy.transpose(arr, axes)

- arr：要操作的数组
- axes：整数列表，对应维度，通常所有维度都会对换。

numpy.ndarray.T 类似 numpy.transpose 转置

numpy.rollaxis(arr, axis, start)

- arr：数组
- axis：要向后滚动的轴，其它轴的相对位置不会改变
- start：默认为零，表示完整的滚动。会滚动到特定位置。

numpy.swapaxes(arr, axis1, axis2)

- arr：输入的数组
- axis1：对应第一个轴的整数
- axis2：对应第二个轴的整数

## 修改数组维度

- broadcast	产生模仿广播的对象
- broadcast_to	将数组广播到新形状
- expand_dims	扩展数组的形状
- squeeze	从数组的形状中删除一维条目

broadcast

broadcast_to(array, shape, subok)将数组广播到新形状。它在原始数组上返回只读视图

expand_dims(arr, axis)通过在指定位置插入新的轴来扩展数组形状

squeeze(arr, axis)从给定数组的形状中删除一维的条目

## 连接数组

- concatenate	连接沿现有轴的数组序列
- stack	沿着新的轴加入一系列数组。
- hstack	水平堆叠序列中的数组（列方向）
- vstack	竖直堆叠序列中的数组（行方向）
concatenate((a1, a2, ...), axis)用于沿指定轴连接相同形状的两个或多个数组

stack(arrays, axis)用于沿新轴连接数组序列，堆叠

numpy.hstack 是 numpy.stack 函数的变体，它通过水平堆叠来生成数组。类似concatenate

numpy.vstack 是 numpy.stack 函数的变体，它通过垂直堆叠来生成数组。

## 分割数组

- split	将一个数组分割为多个子数组
- hsplit	将一个数组水平分割为多个子数组（按列）
- vsplit	将一个数组垂直分割为多个子数组（按行）

numpy.split(ary, indices_or_sections, axis)沿特定的轴将数组分割为子数组
    - ary：被分割的数组
    - indices_or_sections：果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
    - axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
    
hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。

vsplit 沿着垂直轴分割，其分割方式与hsplit用法相同。

## 数组元素的添加与删除

- resize	返回指定形状的新数组
- append	将值添加到数组末尾
- insert	沿指定轴将值插入到指定下标之前
- delete	删掉某个轴的子数组，并返回删除后的新数组
- unique	查找数组内的唯一元素

numpy.resize(arr, shape) 返回指定大小的新数组。如果新数组大小大于原始大小，则包含原始数组中的元素的副本。

numpy.append(arr, values, axis=None)在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 此外，输入数组的维度必须匹配否则将生成ValueError。append 函数返回的始终是一个一维数组。

numpy.insert(arr, obj, values, axis)在给定索引之前，沿给定轴在输入数组中插入值。如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

numpy.delete(arr, obj, axis)返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。

numpy.unique(arr, return_index, return_inverse, return_counts)用于去除数组中的重复元素。

# 位运算

- bitwise_and	对数组元素执行位与操作
- bitwise_or	对数组元素执行位或操作
- invert	按位取反
- left_shift	向左移动二进制表示的位
- right_shift	向右移动二进制表示的位

**注：**也可以使用 "&"、 "~"、 "|" 和 "^" 等操作符进行计算。

np.bitwise_or(13, 17)

np.invert(np.array(\[13\], dtype = np.uint8))

np.left_shift(10,2)

np.binary_repr(10, width = 8)可以获取十进制数的二进制表示

# 字符串函数

以下函数用于对 dtype 为 numpy.string_ 或 numpy.unicode_ 的数组执行向量化字符串操作。 它们基于 Python 内置库中的标准字符串函数。

这些函数在字符数组类（numpy.char）中定义。

- add()	对两个数组的逐个字符串元素进行连接
- multiply()	返回按元素多重连接后的字符串
- center()	居中字符串
- capitalize()	将字符串第一个字母转换为大写
- title()	将字符串的每个单词的第一个字母转换为大写
- lower()	数组元素转换为小写
- upper()	数组元素转换为大写
- split()	指定分隔符对字符串进行分割，并返回数组列表
- splitlines()	返回元素中的行列表，以换行符分割
- strip()	移除元素开头或者结尾处的特定字符
- join()	通过指定分隔符来连接数组中的元素
- replace()	使用新字符串替换字符串中的所有子字符串
- decode()	数组元素依次调用str.decode
- encode()	数组元素依次调用str.encode

# 数学函数

## 三角函数

np.degrees(x) 可以转换为角度制

## 舍入函数

numpy.around(a,decimals) 四舍五入，dec 为小数位数

numpy.floor() 返回数字的下舍整数。

numpy.ceil() 返回数字的上入整数。

# 算数函数

加减乘除: add()，subtract()，multiply() 和 divide()。需要注意的是数组必须具有相同的形状或符合数组广播规则。

numpy.reciprocal() 函数返回参数逐元素的倒数。如 1/4 倒数为 4/1。

numpy.power() 函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。

numpy.mod() 计算输入数组中相应元素的相除后的余数。 函数 numpy.remainder() 也产生相同的结果。

# 统计函数

numpy.amin() 用于计算数组中的元素沿指定轴的最小值。

numpy.amax() 用于计算数组中的元素沿指定轴的最大值。

numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。

numpy.percentile(a, q, axis)百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 a: 输入数组，q: 要计算的百分位数，在 0 ~ 100 之间，axis: 沿着它计算百分位数的轴

numpy.median() 函数用于计算数组 a 中元素的中位数（中值）

numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

numpy.average()函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。

numpy.std()标准差

numpy.var()方差

# 排序、条件刷选函数

numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

numpy.sort(a, axis, kind, order)
参数说明：

a: 要排序的数组
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段

---

numpy.argsort() 函数返回的是数组值从小到大的索引值。

---

numpy.lexsort() 用于对多个序列进行排序。

---

msort(a)	数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。
sort_complex(a)	对复数按照先实部后虚部的顺序进行排序。
partition(a, kth\[, axis, kind, order\])	指定一个数，对数组进行分区
argpartition(a, kth\[, axis, kind, order\])	可以通过关键字 kind 指定算法沿着指定轴对数组进行分区

---

numpy.argmax() 和 numpy.argmin()
numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。

---

numpy.nonzero() 函数返回输入数组中非零元素的索引。

numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。

# 字节交换

numpy.ndarray.byteswap()函数将 ndarray 中每个元素中的字节进行大小端转换。

# 副本和视图
副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。

视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

视图一般发生在：

1、numpy 的切片操作返回原数据的视图。
2、调用 ndarray 的 view() 函数产生一个视图。
副本一般发生在：

Python 序列的切片操作，调用deepCopy()函数。
调用 ndarray 的 copy() 函数产生一个副本。

- b = a 对b的修改会反映在a上
- b = a.view() 视图或浅拷贝，修改b的shape不影响a，但使用切片创建视图会影响原数组
- b = a.copy() 副本或深拷贝，二者互不影响

# 矩阵库

需要import numpy.matlib

numpy.matlib.empty(shape, dtype, order)随机填充

numpy.matlib.zeros() 函数创建一个以 0 填充的矩阵。

numpy.matlib.ones()函数创建一个以 1 填充的矩阵。

numpy.matlib.eye() 函数返回一个矩阵，对角线元素为 1，其他位置为零。

numpy.matlib.identity() 函数返回给定大小的单位矩阵。

numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充的。

# 线性函数

numpy.dot(a, b, out=None) 于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和： dot(a, b)\[i,j,k,m\] = sum(a\[i,j,:\] * b\[k,:,m\])。

numpy.vdot() 函数是两个向量的点积。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数是多维数组，它会被展开。

numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。

numpy.matmul 函数返回两个数组的矩阵乘积。 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。另一方面，如果任一参数是一维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。对于二维数组，它就是矩阵乘法

numpy.linalg.det() 函数计算输入矩阵的行列式。

numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。

numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。

# IO

Numpy 可以读写磁盘上的文本数据或二进制数据。

NumPy 为 ndarray 对象引入了一个简单的文件格式：npy。

npy 文件用于存储重建 ndarray 所需的数据、图形、dtype 和其他信息。

常用的 IO 函数有：

- load() 和 save() 函数是读写文件数组数据的两个主要函数，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npy 的文件中。
- savze() 函数用于将多个数组写入文件，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npz 的文件中。
- loadtxt() 和 savetxt() 函数处理正常的文本文件(.txt 等)

numpy.save(file, arr, allow_pickle=True, fix_imports=True)将数组保存到以 .npy 为扩展名的文件中。

使用 load() 函数来读取数据

---

numpy.savez(file, \*args, \*\*kwds)函数将多个数组保存到以 npz 为扩展名的文件中。

---

savetxt() 函数是以简单的文本文件格式存储数据，对应的使用 loadtxt() 函数来获取数据。

np.loadtxt(FILENAME, dtype=int, delimiter=' ')

np.savetxt(FILENAME, a, fmt="%d", delimiter=",")
